version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - reportes-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # Reportes Microservices
  micro-reportes-estudiantes:
    build:
      context: ./micro-reportes-estudiantes
      dockerfile: Dockerfile
    image: micro-reportes-estudiantes:latest
    container_name: micro-reportes-estudiantes
    restart: unless-stopped
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    networks:
      - reportes-net
    environment:
      NODE_ENV: production
      PORT: 5003
      MONGODB_URI: mongodb://root:example@mongo:27017/reportes-estudiantes?authSource=admin

  micro-reportes-maestros:
    build:
      context: ./micro-reportes-maestros
      dockerfile: Dockerfile
    image: micro-reportes-maestros:latest
    container_name: micro-reportes-maestros
    restart: unless-stopped
    ports:
      - "5004:5004"
    depends_on:
      - mongo
    networks:
      - reportes-net
    environment:
      NODE_ENV: production
      PORT: 5004
      MONGODB_URI: mongodb://root:example@mongo:27017/reportes-maestros?authSource=admin

networks:
  reportes-net:
    driver: bridge

volumes:
  mongo_data:
