version: '3.8'
services:
  frontend:
    image: ${DOCKER_USERNAME}/frontend-web:latest
    container_name: frontend-web
    ports:
      - "5500:5500"
    environment:
      NODE_ENV: production
      API_GATEWAY_URL: http://35.168.216.132:8080
      API_GATEWAY_HOST: 35.168.216.132
      API_GATEWAY_PORT: 8080
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
