version: '3.8'

services:
  # Notificaciones Microservice
  micro-notificaciones:
    build:
      context: ./micro-notificaciones
      dockerfile: Dockerfile
    image: micro-notificaciones:latest
    container_name: micro-notificaciones
    restart: unless-stopped
    ports:
      - "5005:5005"
    networks:
      - notificaciones-net
    environment:
      NODE_ENV: production
      PORT: 5005

networks:
  notificaciones-net:
    driver: bridge
