version: '3.8'

services:
  micro-auth:
    volumes:
      - ./micro-auth:/app:delegated
    environment:
      - NODE_ENV=development
    command: npm start

  api-gateway:
    volumes:
      - ./api-gateway:/app:delegated
    environment:
      - NODE_ENV=development
    command: npm start

  frontend-web:
    volumes:
      - ./frontend-web:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start

  micro-maestros:
    volumes:
      - ./micro-maestros:/app:delegated
    environment:
      - NODE_ENV=development
    command: npm start

  micro-estudiantes:
    volumes:
      - ./micro-estudiantes:/app:delegated
    environment:
      - NODE_ENV=development
    command: npm start

  micro-reportes-estudiantes:
    volumes:
      - ./micro-reportes-estudiantes:/app:delegated
    environment:
      - NODE_ENV=development
    command: npm start

  micro-reportes-maestros:
    volumes:
      - ./micro-reportes-maestros:/app:delegated
    environment:
      - NODE_ENV=development
    command: npm start

  micro-notificaciones:
    volumes:
      - ./micro-notificaciones:/app:delegated
    environment:
      - NODE_ENV=development
    command: npm start

  micro-analytics:
    volumes:
      - ./micro-analytics:/app:delegated
    environment:
      - NODE_ENV=development
    command: npm start

  micro-soap-bridge:
    volumes:
      - ./micro-soap-bridge:/app:delegated
    environment:
      - NODE_ENV=development
    command: npm start
