version: '3.8'

services:
  frontend-web:
    container_name: frontend-web
    image: frontend-web:latest
    network_mode: host
    environment:
      NODE_ENV: production
      API_GATEWAY_URL: http://172.31.76.105:8080
      API_GATEWAY_HOST: 172.31.76.105
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
