global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['172.31.65.190:8080']
    metrics_path: '/metrics'

  - job_name: 'micro-auth'
    static_configs:
      - targets: ['172.31.77.203:5005']
    metrics_path: '/metrics'

  - job_name: 'micro-maestros'
    static_configs:
      - targets: ['172.31.77.203:5001']
    metrics_path: '/metrics'

  - job_name: 'micro-estudiantes'
    static_configs:
      - targets: ['172.31.77.203:5002']
    metrics_path: '/metrics'

  - job_name: 'micro-reportes-estudiantes'
    static_configs:
      - targets: ['172.31.74.228:5003']
    metrics_path: '/metrics'

  - job_name: 'micro-reportes-maestros'
    static_configs:
      - targets: ['172.31.74.228:5004']
    metrics_path: '/metrics'

  - job_name: 'micro-notificaciones'
    static_configs:
      - targets: ['172.31.72.141:5006']
    metrics_path: '/metrics'

  - job_name: 'micro-analytics'
    static_configs:
      - targets: ['172.31.74.228:5007']
    metrics_path: '/metrics'

  - job_name: 'micro-soap-bridge'
    static_configs:
      - targets: ['172.31.72.141:5008']
    metrics_path: '/metrics'

  - job_name: 'message-broker'
    static_configs:
      - targets: ['172.31.72.111:5008']
    metrics_path: '/metrics'