global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'

  - job_name: 'micro-auth'
    static_configs:
      - targets: ['micro-auth:5000']
    metrics_path: '/metrics'

  - job_name: 'micro-maestros'
    static_configs:
      - targets: ['micro-maestros:5001']
    metrics_path: '/metrics'

  - job_name: 'micro-estudiantes'
    static_configs:
      - targets: ['micro-estudiantes:5002']
    metrics_path: '/metrics'

  - job_name: 'micro-reportes-estudiantes'
    static_configs:
      - targets: ['micro-reportes-estudiantes:5003']
    metrics_path: '/metrics'

  - job_name: 'micro-reportes-maestros'
    static_configs:
      - targets: ['micro-reportes-maestros:5004']
    metrics_path: '/metrics'

  - job_name: 'micro-notificaciones'
    static_configs:
      - targets: ['micro-notificaciones:5005']
    metrics_path: '/metrics'

  - job_name: 'micro-analytics'
    static_configs:
      - targets: ['micro-analytics:5006']
    metrics_path: '/metrics'

  - job_name: 'micro-soap-bridge'
    static_configs:
      - targets: ['micro-soap-bridge:5007']
    metrics_path: '/metrics'

  - job_name: 'message-broker'
    static_configs:
      - targets: ['message-broker:5008']
    metrics_path: '/metrics'