global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'proyecto-acompaamiento'
    environment: 'development'

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']

  - job_name: 'microservices'
    static_configs:
      - targets: 
        - 'micro-auth:3000'
        - 'micro-estudiantes:3001'
        - 'micro-maestros:3002'
        - 'micro-reportes-estudiantes:5003'
        - 'micro-reportes-maestros:5004'
        - 'micro-notificaciones:5006'
        - 'micro-analytics:5007'
        - 'micro-soap-bridge:5008'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
