global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Microservices targets to be updated with correct IPs
  # For now, these are commented out to allow Prometheus to start
  # - job_name: 'api-gateway'
  #   static_configs:
  #     - targets: ['api-gateway-ip:8080']
  #   metrics_path: '/metrics'

  # Message broker targets
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:5672']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
