        run: terraform -chdir=terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve -var-file=terraform.tfvars

      - name: Terraform Output
        run: terraform -chdir=terraform output
