name: Deploy Micro Core

on:
  push:
    branches: [ main ]
    paths:
      - micro-core/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Micro Core image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/proyecto-acomp-micro-core:latest ./micro-core
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/proyecto-acomp-micro-core:latest

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MICRO_CORE_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/proyecto-acomp-micro-core:latest
            docker stop micro-core || true
            docker rm micro-core || true
            docker run -d \
              --name micro-core \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/proyecto-acomp-micro-core:latest
